#: import Spinner kivy.uix.spinner

ToolBar:

<ToolBar>
    orientation: "horizontal"
    size_hint: None,None
    spacing: '5dp'
    padding: '5dp'
    pos: (0,550)
    Label:
        text: "Currently\nplacing:"
        size_hint: None,None
        height: '40dp'
    Spinner:
        text: "Wall"
        values: ["Wall","Source","Target","Blank"]
        id: spinner_id
        on_text: root.spinner_clicked(spinner_id.text)
        size_hint: None,None
        height: '40dp'
    Label:
        text: "Current\nalgorithm:"
        size_hint: None,None
        height: '40dp'
    Spinner:
        text: "BFS"
        values: ["BFS","DFS"]
        id: spinner_id2
        on_text: root.spinner_clicked2(spinner_id2.text)
        size_hint: None,None
        height: '40dp'