#: import Spinner kivy.uix.spinner

Select:

<Select>
    orientation: "horizontal"
    size_hint: None,None
    spacing: '5dp'
    padding: '5dp'
    pos: (0,550)
    Label:
        text: "Currently\n placing:"
        size_hint: None,None
        height: '40dp'
    Spinner:
        text: "Wall"
        values: ["Wall","Source","Target","Blank"]
        id: spinner_id
        on_text: root.spinner_clicked(spinner_id.text)
        size_hint: None,None
        height: '40dp'